### ISSUE TITLE
Improve Error Message for invalid syntax

### ISSUE THREAD

**Issue by mulderp** [sideshowcoder/canned#23]
I observe the following:

<pre>
pmu:tmp pmu$ mkdir api
pmu:tmp pmu$ cat > api/posts.json
[ "123" ]
pmu:tmp pmu$ canned
starting canned on port 3000 for ./
request: get /api/posts.json
/usr/local/share/npm/lib/node_modules/canned/lib/response.js:17
  this.cors_enabled = !!options.cors_enabled
                               ^
TypeError: Cannot read property 'cors_enabled' of undefined
    at new Response (/usr/local/share/npm/lib/node_modules/canned/lib/response.js:17:32)
    at /usr/local/share/npm/lib/node_modules/canned/canned.js:194:48
    at Object.oncomplete (fs.js:107:15)
</pre>

Maybe I am missing something?

**Comment by kdeng** [comment]
Any update about this error?
